#!/bin/sh

echo Running core initrd hook
# Import any files bundled in core
for x in /root/pbx/core/meta/systemd/system/*; do
    [ ! -e $x ] && continue
    service=$(basename $x)
    cp $x /root/etc/systemd/system/$service
    # If it has an Install section, enable it
    grep -q Install $x && /root/usr/bin/systemctl --root=/root enable $service
done

# Now loop through everything ELSE in there, and make sure it's activated
for x in /root/etc/systemd/system/*.service; do
    [ ! -f $x ] && continue
    service=$(basename $x)
    grep -q Install $x && /root/usr/bin/systemctl --root=/root enable $service
done

# If core is pushing out a filesystem update, AND it's not disabled by
# kernel params, merge them across
if [ -d /root/pbx/core/filesystem ]; then
    grep -q skipfs /proc/cmdline && rsync -av /root/pbx/core/filesystem/ /root/
fi

scfix=/root/pbx/core/bin/siteconf.sh
if [ -x $scfix ]; then
    echo "Running Siteconf fixer $scfix"
    $scfix
fi
